### ISSUE TITLE
NullPointerException - removing after stopped

### ISSUE THREAD

**Issue by jurajcik** [tuwiendsg/rSYBL#6]
When I want to stop control of a service and remove it afterwards, server returns status 500.
I'm using these operations:
- stopping: PUT ... /{id}/stopControl
- removing: DELETE ... /managedService/{id}

Server returns stacktrace:
java.lang.NullPointerException
	at.ac.tuwien.dsg.rSybl.analysisEngine.main.ControlService.removeFromMonitoring(ControlService.java:150)
	at.ac.tuwien.dsg.rSybl.analysisEngine.main.ControlCoordination.removeService(ControlCoordination.java:30)
	at.ac.tuwien.dsg.rSybl.analysisEngine.webAPI.SyblControlWS.removeServiceFromControl(SyblControlWS.java:155)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	java.lang.reflect.Method.invoke(Unknown Source)
	com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
	com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$VoidOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:167)
...

**Comment by GeorgianaCopil** [comment]
Fixed with commit d6cb83857a92b5c9628567290ecc14fe71069b9d
